export const constants = {
    ADD_POST: "ADD_POST",
    REMOVE_POST: "REMOVE_POST",
    EDIT_POST: "UPDATE_POST",
    REQUEST_POSTS: "REQUEST_POSTS",
    COMPLETE_POSTS: "COMPLETE_POSTS",
    RECEIVE_POSTS: "RECEIVE_POSTS",
    REQUEST_TOPICS: "REQUEST_TOPICS",
    COMPLETE_TOPICS: "COMPLETE_TOPICS",
    RECEIVE_TOPICS: "RECEIVE_TOPICS",
    CLEAR_FILTER: "CLEAR_FILTER",
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
    ADD_TOPIC: "ADD_TOPIC",
    UPDATE_TOPIC: "UPDATE_TOPIC",
    REMOVE_TOPIC: "REMOVE_TOPIC"
}

export const visibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  DENIAL: 'DENIAL',
  SELF_ESTEEM: 'SELF_ESTEEM',
  COMPLIANCE: "COMPLIANCE",
  CONTROL: "CONTROL",
  AVOIDANCE: "AVOIDANCE",
  ANXIETY: "ANXIETY",
  DEPRESSION: "DEPRESSION"
}
